name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # 每天 UTC 00:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      # GitHub Stats（暗色）
      - name: Generate stats card (dark)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: >
            username=KinhoLeung
            &hide_border=true
            &show_icons=true
            &card_width=400
            &theme=vue-dark
            &rank_icon=github
            &ring_color=1ED760
            &title_color=1ED760
            &icon_color=1ED760
            &bg_color=00000000
          path: profile/stats-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # GitHub Stats（亮色）
      - name: Generate stats card (light)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: >
            username=KinhoLeung
            &hide_border=true
            &show_icons=true
            &card_width=400
            &theme=vue
            &rank_icon=github
            &ring_color=1ED760
            &title_color=1ED760
            &icon_color=1ED760
            &bg_color=00000000
          path: profile/stats-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Top Languages（暗色）
      - name: Generate top languages card (dark)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: >
            username=KinhoLeung
            &layout=compact
            &langs_count=6
            &theme=vue-dark
            &hide_border=true
            &title_color=1ED760
            &icon_color=1ED760
            &bg_color=00000000
          path: profile/top-langs-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Top Languages（亮色）
      - name: Generate top languages card (light)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: >
            username=KinhoLeung
            &layout=compact
            &langs_count=6
            &theme=vue
            &hide_border=true
            &title_color=1ED760
            &icon_color=1ED760
            &bg_color=00000000
          path: profile/top-langs-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
